# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: events.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x65vents.proto\"R\n\x1blocationEventServiceMessage\x12\x0e\n\x06userid\x18\x01 \x01(\x05\x12\x10\n\x08latitude\x18\x02 \x01(\x05\x12\x11\n\tlongitude\x18\x03 \x01(\x05\x32T\n\x0c\x65ventService\x12\x44\n\x06\x43reate\x12\x1c.locationEventServiceMessage\x1a\x1c.locationEventServiceMessageb\x06proto3')



_LOCATIONEVENTSERVICEMESSAGE = DESCRIPTOR.message_types_by_name['locationEventServiceMessage']
locationEventServiceMessage = _reflection.GeneratedProtocolMessageType('locationEventServiceMessage', (_message.Message,), {
  'DESCRIPTOR' : _LOCATIONEVENTSERVICEMESSAGE,
  '__module__' : 'events_pb2'
  # @@protoc_insertion_point(class_scope:locationEventServiceMessage)
  })
_sym_db.RegisterMessage(locationEventServiceMessage)

_EVENTSERVICE = DESCRIPTOR.services_by_name['eventService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _LOCATIONEVENTSERVICEMESSAGE._serialized_start=16
  _LOCATIONEVENTSERVICEMESSAGE._serialized_end=98
  _EVENTSERVICE._serialized_start=100
  _EVENTSERVICE._serialized_end=184
# @@protoc_insertion_point(module_scope)
