apiVersion: v1
kind: Service
metadata:
  labels:
    service: udaconnect_location_event_producer
  name: udaconnect_location_event_producer
spec:
  ports:
  - name: "5005"
    port: 5005
    targetPort: 5005
    nodePort: 30008
  selector:
    service: udaconnect_location_event_producer
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: udaconnect_location_event_producer
  name: udaconnect_location_event_producer
spec:
  replicas: 1
  selector:
    matchLabels:
      service: udaconnect_location_event_producer
  template:
    metadata:
      labels:
        service: udaconnect_location_event_producer
    spec:
      containers:
      - image: rmukkamala/udaconnect_location_event_producer:latest
        name: udaconnect_location_event_producer
        imagePullPolicy: Always
        env:
        - name: KAFKA_URL
          valueFrom:
            configMapKeyRef:
              name: location_event_producer_map
              key: KAFKA_URL
        - name: KAFKA_TOPIC
          valueFrom:
            configMapKeyRef:
              name: location_event_producer_map
              key: KAFKA_TOPIC
        - name: PYTHONUNBUFFERED
          value: '0'
      restartPolicy: Always