apiVersion: v1
kind: Service
metadata:
  labels:
    service: udaconnect-location-event-producer
  name: udaconnect-location-event-producer
spec:
  ports:
  - name: "5005"
    port: 5005
    targetPort: 5005
    nodePort: 30008
  selector:
    service: udaconnect-location-event-producer
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: udaconnect-location-event-producer
  name: udaconnect-location-event-producer
spec:
  replicas: 1
  selector:
    matchLabels:
      service: udaconnect-location-event-producer
  template:
    metadata:
      labels:
        service: udaconnect-location-event-producer
    spec:
      containers:
      - image: rmukkamala/udaconnect-location-event-producer:latest
        name: udaconnect-location-event-producer
        imagePullPolicy: Always
        #imagePullPolicy: "IfNotPresent"
        env:
        - name: KAFKA_URL
          valueFrom:
            configMapKeyRef:
              name: location-event-producer-map
              key: KAFKA_URL
        - name: KAFKA_TOPIC
          valueFrom:
            configMapKeyRef:
              name: location-event-producer-map
              key: KAFKA_TOPIC
      restartPolicy: Always
