apiVersion: v1
kind: Service
metadata:
  labels:
    service: udaconnect-location-event-consumer
  name: udaconnect-location-event-consumer
spec:
  ports:
  - name: "5005"
    port: 5005
    targetPort: 5005
  selector:
    service: udaconnect-location-event-consumer
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: udaconnect-location-event-consumer
  name: udaconnect-location-event-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      service: udaconnect-location-event-consumer
  template:
    metadata:
      labels:
        service: udaconnect-location-event-consumer
    spec:
      containers:
      - image: rmukkamala/udaconnect-location-event-consumer:latest
        name: udaconnect-location-event-consumer
        imagePullPolicy: Always
        #imagePullPolicy: "IfNotPresent"
      restartPolicy: Always