apiVersion: v1
kind: Service
metadata:
  labels:
    service: udaconnect_location_event_consumer
  name: udaconnect_location_event_consumer
spec:
  ports:
  - name: "5005"
    port: 5005
    targetPort: 5005
  selector:
    service: udaconnect_location_event_consumer
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: udaconnect_location_event_consumer
  name: udaconnect_location_event_consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      service: udaconnect_location_event_consumer
  template:
    metadata:
      labels:
        service: udaconnect_location_event_consumer
    spec:
      containers:
      - image: rmukkamala/udaconnect_location_event_consumer:latest
        name: udaconnect_location_event_consumer
        imagePullPolicy: Always
        env:
        - name: KAFKA_URL
          valueFrom:
            configMapKeyRef:
              name: person-location-event-map
              key: KAFKA_URL
        - name: KAFKA_TOPIC
          valueFrom:
            configMapKeyRef:
              name: person-location-event-map
              key: KAFKA_TOPIC
        - name: PYTHONUNBUFFERED
          value: '0'
      restartPolicy: Always