apiVersion: v1
kind: ConfigMap
data:
  DB_USERNAME: "ct_admin"
  DB_NAME: "geoconnections"
  DB_HOST: "postgres"
  DB_PORT: "5432"
  KAFKA_URL: "kafka-service.default.svc.cluster.local:9092"
  KAFKA_TOPIC: "event"
metadata:
  name: location-event-producer-map